# Site settings
title: Matt and Katrina
email: mattm86@gmail.com
url: http://www.mcnuttsabouteachother.com
description: "We're getting married and can't wait to celebrate with you!"
baseurl: ""
host: 0.0.0.0 # listen to LAN connections
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
encoding: bom|utf-8

# Possible values
# `chi` - Chicago
# `lbc` - Long Beach
# 'cos' - Colorado Springs, CO
# 'wp' - Woodland Park, CO
context: wp

locations:
  country_lodge: &country_lodge_location
    location_name: Country Lodge
    address1: 723 US-24
    address2: Woodland Park, CO 80863
    coordinates: 38.9898827,-105.0612779
    google_maps_url: https://www.google.com/maps/place/Country+Lodge/@38.9898827,-105.0612779,14z/data=!4m8!1m2!2m1!1shotel!3m4!1s0x8714aac895342131:0x766425a95f233925!8m2!3d38.9894774!4d-105.0601413!6m1!1e1
  comfort_inn: &comfort_inn_location
    location_name: Comfort Inn
    address1: 45 Manitou Ave
    address2: Manitou Springs, CO 80829
    coordinates: 38.8550654,-104.9829224
    google_maps_url: https://www.google.com/maps/place/Comfort+Inn/@38.8550654,-104.9829224,12z/data=!4m8!1m2!2m1!1scomfort+inn!3m4!1s0x0:0x898c5d539c8639ff!8m2!3d38.8569872!4d-104.8908305
  antlers: &antlers_location
    location_name: Antlers
    address1: 4 S Cascade Ave
    address2: Colorado Springs, CO 80903
    coordinates: 38.83364,-104.8289937
    google_maps_url: https://www.google.com/maps/place/The+Antlers+Colorado+Springs/@38.83364,-104.8289937,17z/data=!3m1!4b1!4m5!3m4!1s0x871345236a82b32f:0x8e6494578dfd44b0!8m2!3d38.83364!4d-104.826805

hotels:
  wp:
    - name: Country Lodge
      phone: +1-719-687-6277
      reserve_url: http://www.woodlandcountrylodge.com/
      rate: $/night
      description: Includes continental breakfast each morning, Closest to the venu, shuttle will be provided to venue
      <<: *country_lodge_location
    - name: Comfort Inn
      phone: +1-719-685-5455
      reserve_url: https://www.choicehotels.com/colorado/manitou-springs/comfort-inn-hotels/co196?source=gyxt
      rate: $118/night
      description: Includes continental breakfast each morning, Closest to the brides parents
      <<: *comfort_inn_location
    - name: The Antlers Colorado Springs
      phone: +1-719-955-5600
      reserve_url: http://antlers.com/
      rate: $116/night
      description: Closest to Downtown, Airport, Farthest from the venue
      <<: *antlers_location

events:
  wp:
    - name: Wedding
      date: Saturday, July 1, 2017
      time: TBD
      attire: Black Tie Optional
      description:
      transportation: Self-parking will be available
      shuttle: Transportation will also be provided between Country Lodge and Venue
      # <<: *wedding_location
    - name: Reception
      date: Saturday, July 1, 2017
      time: TBD
      attire: Black Tie Optional
      description: Join us for dinner and dancing as we celebrate our marriage into the night!
      transportation: Self-parking will be available
      shuttle: Transportation will also be provided between Country Lodge and Venue
      # <<: *wedding_location
    # - name: Mehndi Night
    #   date: Thursday, May 26, 2016
    #   time: 7pm
    #   attire: Casual
    #   description: A casual family gathering where henna is applied in intricate designs to the hands and feet of the bride and her female guests. Meant as one of many ritual adornments for the Hindu bride, it is said that the darker the henna turns out, the greater the love the bride has for her groom.  Mehndi artists also hide the groom’s name or initials into the bride’s henna design and it is her job to find them before the wedding. Traditionally, the bride is not allowed to work in her husband’s house until after the mehndi has completely faded. Further, with their hands covered in henna paste, the women of the party are unable to cook or serve during the Mehndi celebration, so the men are invited to feed and serve the women.
    #   transportation:
    #   <<: *vashi_location


people:
  families:
    - pic: hoang.jpg
      name: The Berendts
      people: Katrina, April, Steven, Betty
    - pic: hoang.jpg
      name: The McNutts
      people: Matthew, Robert, Angus, Jenny
  kids:
    - pic: hoang.jpg
      name: Helena Clemmensen
      title: Flower Girl
    - pic: isabelle.jpg
      name: Isabelle McNutt
      title: Flower Girl
    - pic: elizabeth.jpg
      name: Elizabeth McNutt
      title: Junior Bridesmaid
  her_side:
    - name: April Clemmensen
      pic: april.jpg
      role: Maid of Honor
      description: Katrina's Sister
    - name: Sara Svatos
      pic: sara.jpg
      role: Bridesmaid
      description: Katrina's Childhood Friend
    - name: Jessica Theis
      pic: jess.jpg
      role: Bridesmaid
      description: Katrina's Childhood Friend
    - name: Molly McIntyre
      pic: molly.jpg
      role: Bridesmaid
      description: Katrina's College Roommate
    - name: Chelsea Baker
      pic: chelsea.jpg
      role: Bridesmaid
      description: Katrina's Army Roommate
  his_side:
    - name: Hoang Nguyen
      pic: hoang.jpg
      role: Best Man
      description: Matt's Childhood Friend
    - name: Sipo Thao
      pic: sipo.jpg
      role: Groomsman
      description: Matt's College Friend
    - name: Carl Cassler
      pic: carl.jpg
      role: Groomsman
      description: Matt's Childhood Friend
    - name: George Martinez
      pic: george.jpg
      role: Groomsman
      description: Matt's College Friend
    - name: Tony Sek
      pic: tony.jpg
      role: Groomsman
      description: Matt's Deployment Friend

faq:
  wp:
    - question: OMG what do I wear?
      answer: |
        The Wedding ceremony and reception on Saturday will be a little more formal.

        <strong>Ladies</strong>: Wear your formal evening wear!  If you've got a full-length gown hanging in the back of your closet, this would be a great opportunity to break it out. No color restrictions here (except maybe not white - don't want to be confused for the bride!).
        <strong>Gentlemen</strong>: Jacket and ties are encouraged. For those with a tuxedo, this would be a good time to dust that off too, but it's by no means required to get past the bouncers (There won't be any bouncers.)
    - question: |
        I have a pretty seriously allergy to [insert allergen here], can you accomodate me?
      answer: |
        Yes! Get in touch with us ASAP, so we can make sure we keep any [insert allergen here] away from you!
    - question: Should I rent a car?
      answer: |
        Our recommendation is yes. If you choose to stay at the Country Lodge transportation will be provided to the wedding site. However if you are staying anywhere else or want some wheels to see what Colorado has to offer than we suggest a rental car as other options are limited.
        Uber and Lyft will be limited in and around the Wedding venue.
    - question: You decided to have your wedding XXX(X?) miles away and I cant find a babysitter for 3 days.  Can I bring kids to the wedding?
      answer: |
        Yes! We will be supplying complimentary babysitting for the ceremony and reception at the venue location.  The little ones can hangout with you or the other kiddos and caretaker for as much or as little as you like.  Now you don’t have that excuse not to come.
  lbc: false

guide:
  chi:
    explore:
      - title: Millenium Park & Cloud Gate
        description: While lots of visitors come to see "The Bean," there's a lot more to see at Millenium Park including giant screens of people spitting on you (yes, that's a real thing), the Lurie Garden and Pritzker Pavillion. And while you're there, it might also be a good time to cross the street and check out Maggie Daley Park.
      - title: Maggie Daley Park
        description: This park just opened a few years ago, and is a must-see for kids with a large portion of it dedicated to play areas for children. While the ice skating ribbon is popular in the winter, there are also rock climbing walls and tennis courts to keep you busy in the summer months.
      - title: Grant Park & Buckingham Fountain
        description: Stretching from just south of Navy Pier all the way to Museum Campus, don't be surprised to see one or two events going on at any given time. If you're staying anywhere in the loop and looking for some exercise, you won't be alone walking or jogging around the park at any time of day either. And don't forget to check out Buckingham Fountain as well, another iconic Chicago landmark.
      - title: River Cruise Architecture Tour
        description: Another must-do for anyone visiting Chicago! Enjoy views of the city's sky scrapers and learning about the Chicago history while cruising down the Chicago River. There are a few different companies that offer architecture cruises, but our favorite is the one run by the <a href="https://www.architecture.org/experience-caf/tours/detail/chicago-architecture-foundation-river-cruise-aboard-chicagos-first-lady-cruises/">Chicago Architecture Foundation on Chicago's First Lady</a>.
      - title: Navy Pier
        description: Yes, the reception on Sunday is going to be at the Navy Pier Ballroom, but there's so much more to do here! Memorial day weekend just happens to be the grand opening of the new-and-improved Ferris Wheel celebrating the pier's 100th anniversary. For the kids, there are rides, games, laser tag, a children's museum and more.
      - title: Magnificent Mile
        description: If your idea of a good time is shopping 'til you drop, then this is the place for you. Starting at the river and running all the way down Michigan Avenue until Oak Street is almost every store you could imagine. The John Hancock building also sits on the north end of Michigan Avenue, if you need a break from spending all that dough. Keep an eye out for the original water tower, which is one of only a few structures in the city that survived the Great Chicago Fire.
      - title: Lincoln Park (and Zoo)
        description: While not really walking distance from the Loop, if you make it out to Linoln Park (a short uber-ride away) you won't be disappointed. Lincoln Park is a beautiful place for a walk or run, highlighted by the zoo, which sits in the center of the park and is free to the public. Check out the monkeys, tigers, giraffes and more!
      - title: John Hancock Center
        description: The fourth tallest building in Chicago, there are a few restaurants and stores on the ground level, but the real sights to see are on 94th floor at the 360˚ Chicago observation deck where, you guessed it, you can get a 360 degree view of the city. And, for those that need a little more exictement in their life, you can check out Tilt, which will lean you out the base of the building 30 degrees to see eveything straight to the bottom. For those less adventurous, grab a drink at the Signature Lounge on the 96th floor or a bite at the Signature Room on the 95th floor. Time it right and you'll get a fantastic view of the sunset.
      - title: Willis Tower
        description: Even though all the cool kids still call it Sears Tower, it's new name doesn't change the fact that it's still the tallest building in Chicago. Similar to the John Hancock, The Sky Deck on the 103rd floor of Willis Tower also gives a 360 degree view of the city from the southern part of the Loop. The Ledge in the Sky Deck takes Tilt one step further and actually puts you in a glass balcony, letting you stare straight past your feet to the sidewalk below.
      - title: The Second City
        description: Don't let the name fool you - The Second City is a legendary improv and comedy club that's been the starting point for some of the world's greatest comedians, both past and present. Many of your favorite Saturday Night Live comedians originated here. You can catch a stand-up comedy show or watch one of the many improv shows they put on throught the week.
    food:
      - title: Deep Dish Pizza
        description: This is what Chicago is known for. The classic debate is between Giordano's and Lou Malnati's (we both prefer Giordano's), so if you're looking to start your deep dish adventure somewhere, we'd suggest one of those two. There are multiple locations throughout the city.
      - title: Italian Beef
        description: Another Chicago staple. When staying in Chicago for the first time, a visit to Portillo's is almost required just to experience the fast-food/amusement park atmosphere inside. For something less touristy, hit up any of the Al's Beef locations in the city. While the establishments are  typically not much to look at, a beef dipped with hot and sweet peppers will make you think you're in sandwich heaven.
      - title: Steakhouses
        description: If you want a steak, you've come to thr right town. From national chains to Chicago-only classics, there's almost too many to choose from. For something that you can't find outside of Chicago, we recommend Chicago Cut Steakhouse, where you might find yourself sitting next to celebrities (Obama eats here every time he's in town!) while overlooking the Chicago River. For a good steak in a not-so-traditional, speakeasy setting, try Bavette's Bar and Boeuf.
      - title: Eataly
        description: It's like Italy but with "eat" at the front, get it?! Jokes aside, the grocery store/food court/restaurant is like walking into a mini outdoor market. Each restaurant in the building is set up along the same aisles that hold the food used to prepare your meals. Come for the amazing pasta and pizza, stay for the gelato and Nutella Bar. Be warned, Eataly does get crowded on the weekends.
      - title: Xoco, Tompolobampo, Frontera Grill
        description: Rick Bayless has redefined Mexican cuisine in Chicago and around the country. These are his signature three restaurants. Xoco is a casual lunch spot where you can pick a torta (sandwich). Frontera Grill takes a limited number of reservations, but is mostly first come, first served, so plan on coming an hour or so before you want to eat. Tompolobampo is a fancier, sit-down meal and typically requires reservations unless you show up at 4:30 with the hopes of getting one of the walk in tables.
      - title: Girl and the Goat & Little Goat
        description: Girl and the Goat is the restaurant that Stephanie Izard opened after winning Top Chef Season Four and serves an eclectic menu, including a section dedicated to, you guessed it, goat. Reservations are hard to come by, but you might be able to snag a table at the bar area if you show up around 4:30pm or 10:00pm. But whatever you do, make sure you get the green beans! If you want something a little less high maintenance, she also owns a newer diner-style restaurant right across the street called Little Goat as well as a brand new Chinese restaurant down the street called Duck Duck Goat.
      - title: Au Cheval
        description: The restaurant is dimly lit and typically cramped with music blaring from the speakers. They don't take reservations and you'll probably end up waiitng at least an hour and a half for a table. BUT if you can stomach all those things, get the double cheeseburger with bacon, an egg and (if you're daring) foie gras. That's the one that's been called the best burger in America.
      - title: Big Star
        description: Situated a little further away from the action of the weekend in Wicker Park, if you make the treck out on the Blue Line, you'll be rewarded with margaritas, cold beers and some of the best tacos in the city. If the weather is nice, you can enjoy all this and more while sitting on their huge patio.
        title: Brunch/Coffee
          description:|
            Craving eggs and coffee? There are more options than we have time to offer!  A famous choice, with several locations around the city, is Yolk, but you'll end up waiting for an hour on a Saturday or Sunday morning. For a traditional brunch without the wait, try Eggy's. Tucked away in the heart of Lakeshore East, this place is in our backyard and we're likely there on any given Sunday (try the chilaquiles!). For a meatier brunch, try The Publican in West Loop - they're known for their thick-cut bacon. Want both savory and sweet? Check out Cafe Ba-Ba-Reeba in Lincoln Park. A well-known tapas place, they also secretly serve brunch with tapas-sized portions that allow you to order eggs AND pancakes. For a quick cup of coffee, try Intelligentsia (also served at many brunch spots) or Dollop Cafe.
    drinks:
      - title: Rooftops
        description: When the weather cooperates, everyone in the city heads straight to the roofs. Check out the Roof at the Wit if you're looking for a sheek, ultra-lounge feel. The IO Lounge at the Godfrey lets you hedge your bets as far as weather is concerend with an outdoor and indoor area. Cindy's on the roof of the Chicago Athletic Association Hotel on Michigan Avenue serves great drinks and has a great view of Grant Park, Lake Michigan and beyond.
      - title: Pops for Champagne & Watershed
        description: We're celebrating a wedding, why not have some champagne? Pops serves champagne, sparkling wine and cocktails featuring them both. If that's not your fancy, look for the black W and head downstairs to somewhat-hidden Watershed, which features comfy seats, a sizable local beer selection, and some of the best whiskeys around.
      - title: Hubbard Street
        description: Just north of the loop across the Chicago River is where you'll find the bars and clubs of the River North neighborhood on and around Hubbard Street. Combined with the slew of restaurants in and around River North, you can easily make a night of wandering the scene here. Social 25 and Rockit are centrally located and good if you're looking for some drinks and dancing, but you can generally find both at most places on Hubbard Street as well.  Lines got you down?  Try Mercer 311 (usually no line, no cover, and great music).
      - title: Breweries
        description: Goose Island is a Chicago staple and has a new tasting room in West Loop that also offers tours of it's facilities.  Goose Island also offers a full-service restaurant that serves up its famous brews, for those of you worried about bringing children to a tasting room. Revolution Brewery is also a local favorite and has a tap room and brewery tours a little further from downtown. Lagunitas recently opened a huge brewery in Chicago as well that features an equally huge taproom.
      - title: The Aviary
        description: From the same people who operate Alinea, which has been named best restaurant in the country, The Aviary serves creatively designed cocktails that will likely have you telling stories about the drinks you experienced there. They do take a few walk-ins, but your best bet is to buy tickets ahead of time, which is effectively a deposit toward your drinks and snacks for the night.

  lbc: false

google:
  key: AIzaSyCn2Z9McwWAC-i_7FE0-ug5lN1M57gb0xo

#calendar:
#  ical: https://www.google.com/calendar/ical/baclig.com_fqi9g8u7mre0m4oaqj1p66608c%40group.calendar.google.com/public/basic.ics
#  google_id: baclig.com_fqi9g8u7mre0m4oaqj1p66608c@group.calendar.google.com
