# Site settings
title: Matt and Katrina
email: mattm86@gmail.com
url: http://www.mcnuttsabouteachother.com
description: "We're getting married and can't wait to celebrate with you!"
baseurl: ""
host: 0.0.0.0 # listen to LAN connections
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
encoding: bom|utf-8

# Possible values
# `chi` - Chicago
# `lbc` - Long Beach
# 'cos' - Colorado Springs, CO
# 'wp' - Woodland Park, CO
context: wp

locations:
  country_lodge: &country_lodge_location
    location_name: Country Lodge
    address1: 723 US-24
    address2: Woodland Park, CO 80863
    coordinates: 723+US-24+Woodland Park,+CO+80863
    google_maps_url: https://www.google.com/maps/place/Country+Lodge/@38.9898827,-105.0612779,14z/data=!4m8!1m2!2m1!1shotel!3m4!1s0x8714aac895342131:0x766425a95f233925!8m2!3d38.9894774!4d-105.0601413!6m1!1e1
  comfort_inn: &comfort_inn_location
    location_name: Comfort Inn
    address1: 45 Manitou Ave
    address2: Manitou Springs, CO 80829
    coordinates: 45+Manitou+Ave+Manitou+Springs,+CO+80829
    google_maps_url: https://www.google.com/maps/place/Comfort+Inn/@38.8550654,-104.9829224,12z/data=!4m8!1m2!2m1!1scomfort+inn!3m4!1s0x0:0x898c5d539c8639ff!8m2!3d38.8569872!4d-104.8908305
  antlers: &antlers_location
    location_name: Antlers
    address1: 4 S Cascade Ave
    address2: Colorado Springs, CO 80903
    coordinates: 4+S+Cascade+Ave+Colorado+Springs,+CO+80903
    google_maps_url: https://www.google.com/maps/place/The+Antlers+Colorado+Springs/@38.83364,-104.8289937,17z/data=!3m1!4b1!4m5!3m4!1s0x871345236a82b32f:0x8e6494578dfd44b0!8m2!3d38.83364!4d-104.826805
  golf_course: &wedding_location
    location_name: Shining Mountain Golf Club
    address1: 100 Shining Mountain Ln,
    address2: Woodland Park, CO 80863
    coordinates: 100+Shining+Mountain+Ln,+Woodland+Park,+CO+80863
    google_maps_url: https://www.google.com/maps/place/Shining+Mountain+Golf+Club/@39.020417,-105.0716907,17z/data=!3m1!4b1!4m5!3m4!1s0x876b55193152768d:0xbddcbb8b603b2c31!8m2!3d39.020417!4d-105.069502
  eagle_fire: &eagle_fire_location
    location_name: Eagle Fire Lodge and Cabins
    address1: 777 US-24, Woodland Park, CO 80863
    address2: Woodland Park, CO 80863
    coordinates: 777+US-24,+Woodland+Park,+CO+80863
    google_maps_url: https://www.google.com/maps/place/Eagle+Fire+Lodge+%26+Cabins/@38.987347,-105.0493317,17z/data=!3m1!4b1!4m5!3m4!1s0x8714aaba57010571:0xefe934e9a896c992!8m2!3d38.987347!4d-105.047143

hotels:
  wp:
    - name: Country Lodge
      phone: +1-719-687-6277
      reserve_url: http://www.woodlandcountrylodge.com/
      rate: $145/night
      description: Includes continental breakfast each morning, Closest to the venu, shuttle will be provided to venue
      <<: *country_lodge_location
    - name: Eagle Fire Lodge and Cabins
      phone: +1-719-687-5700
      reserve_url: https://www.eaglefirelodge.com/
      rate: $95/night
      description: Includes continental breakfast each morning, Closest to the venu, shuttle will be provided to venue
      <<: *eagle_fire_location
    - name: Comfort Inn
      phone: +1-719-685-5455
      reserve_url: https://www.choicehotels.com/colorado/manitou-springs/comfort-inn-hotels/co196?source=gyxt
      rate: $118/night
      description: Includes continental breakfast each morning, Closest to the brides parents
      <<: *comfort_inn_location
    - name: The Antlers Colorado Springs
      phone: +1-719-955-5600
      reserve_url: http://antlers.com/
      rate: $116/night
      description: Closest to Downtown, Airport, Farthest from the venue
      <<: *antlers_location

events:
  wp:
    - name: Wedding
      date: Saturday, July 1, 2017
      time: 4:00 PM
      attire: Black Tie Optional
      description:
      transportation: Self-parking will be available
      shuttle: Transportation will also be provided between Country Lodge, Eagle Fire Lodge and Venue
      <<: *wedding_location
    - name: Reception
      date: Saturday, July 1, 2017
      time: 5:00 PM
      attire: Black Tie Optional
      description: Join us for dinner and dancing as we celebrate our marriage into the night!
      transportation: Self-parking will be available
      shuttle: Transportation will also be provided between Country Lodge, Eagle Fire Lodge and Venue
      <<: *wedding_location
    # - name: Mehndi Night
    #   date: Thursday, May 26, 2016
    #   time: 7pm
    #   attire: Casual
    #   description: A casual family gathering where henna is applied in intricate designs to the hands and feet of the bride and her female guests. Meant as one of many ritual adornments for the Hindu bride, it is said that the darker the henna turns out, the greater the love the bride has for her groom.  Mehndi artists also hide the groom’s name or initials into the bride’s henna design and it is her job to find them before the wedding. Traditionally, the bride is not allowed to work in her husband’s house until after the mehndi has completely faded. Further, with their hands covered in henna paste, the women of the party are unable to cook or serve during the Mehndi celebration, so the men are invited to feed and serve the women.
    #   transportation:
    #   <<: *vashi_location


people:
  families:
    - pic: hoang.jpg
      name: The Berendts
      people: Katrina, April, Steven, Betty
    - pic: hoang.jpg
      name: The McNutts
      people: Matthew, Robert, Angus, Jenny
  kids:
    - pic: hoang.jpg
      name: Helena Clemmensen
      title: Flower Girl
    - pic: isabelle.JPG
      name: Isabelle McNutt
      title: Flower Girl
    - pic: elizabeth.JPG
      name: Elizabeth McNutt
      title: Junior Bridesmaid
  her_side:
    - name: April Clemmensen
      pic: april.jpg
      role: Maid of Honor
      description: Katrina's Sister
    - name: Sara Svatos
      pic: sara.JPG
      role: Bridesmaid
      description: Katrina's Childhood Friend
    - name: Jessica Theis
      pic: jess.jpg
      role: Bridesmaid
      description: Katrina's Childhood Friend
    - name: Molly McIntyre
      pic: molly.jpg
      role: Bridesmaid
      description: Katrina's College Roommate
    - name: Chelsea Baker
      pic: chelsea.JPG
      role: Bridesmaid
      description: Katrina's Army Roommate
  his_side:
    - name: Hoang Nguyen
      pic: hoang.jpg
      role: Best Man
      description: Matt's Childhood Friend
    - name: Sipo Thao
      pic: sipo.jpg
      role: Groomsman
      description: Matt's College Friend
    - name: Craig Jensen
      pic: hoang.jpg
      role: Groomsman
      description: Matt's College Friend
    - name: George Martinez
      pic: george.jpg
      role: Groomsman
      description: Matt's College Friend
    #- name: Tony Sek
    #  pic: tony.jpg
    #  role: Groomsman
    #  description: Matt's Deployment Friend

faq:
  wp:
    - question: OMG what do I wear?
      answer: |
        The Wedding ceremony and reception on Saturday will be a little more formal.

        <strong>Ladies</strong>: Wear your formal evening wear!  If you've got a full-length gown hanging in the back of your closet, this would be a great opportunity to break it out. No color restrictions here (except maybe not white - don't want to be confused for the bride!).
        <strong>Gentlemen</strong>: Jacket and ties are encouraged. For those with a tuxedo, this would be a good time to dust that off too, but it's by no means required to get past the bouncers (There won't be any bouncers.)
    - question: |
        I have a pretty seriously allergy to [insert allergen here], can you accomodate me?
      answer: |
        Yes! Get in touch with us ASAP, so we can make sure we keep any [insert allergen here] away from you!
    - question: Should I rent a car?
      answer: |
        Our recommendation is yes. If you choose to stay at the Country Lodge or Eagle Fire Lodge and Cabins transportation will be provided to the wedding site. However if you are staying anywhere else or want some wheels to see what Colorado has to offer than we suggest a rental car as other options are limited.
        Uber and Lyft will be limited in and around the Wedding venue.
    - question: You decided to have your wedding XXX(X?) miles away and I cant find a babysitter for 3 days.  Can I bring kids to the wedding?
      answer: |
        Yes! We will be supplying complimentary babysitting for the ceremony and reception at the venue location.  The little ones can hangout with you or the other kiddos and caretaker for as much or as little as you like.  Now you don’t have that excuse not to come.
  lbc: false

guide:
  wp:
    explore:
      - title: Olympic Training Center
        description: The tour starts with an inspirational 12-minute film and then a 45-minute outdoor walking tour of the training complex, including the weightlifting and wrestling facilities, the Aquatics Center and the Sport Center Gymnasiums. Visitors can then explore the U.S. Olympic Hall of Fame Rotunda, shop at the U.S. Olympic Store and check out the ever-changing art exhibitions found throughout the Olympic Visitor Center.
      - title: Seven Falls
        description: Bask in the majesty of Seven Falls, a magnificent series of cascading waterfalls located in a 1,400-foot-wall box canyon, and  explore everything else the new Seven Falls has to offer. From delectable new dining options—including the exquisite new Restaurant 1858, gift shops, walking and hiking trails, the optional Broadmoor Soaring Adventure—a thrilling exploration above Seven Falls, that includes hiking, following rope bridges, and culminating inside Seven Falls Park.
      - title: Cheyenne Mountain Zoo
        description: A beautiful zoo with over 30 endangered species to explore, all while over looking Colorado Springs.
      - title: Old Colorado City
        description: Visit the historical old Colorado city with dozens of shops and restaurants as well as various cultural events in the park!
      - title: The Incline
        description: Hike a mile straight up the beautiful rocky mountains at the base of Pikes Peak. the view is worth the trip! Take the Bar trail down for a full hiking adventure.
      - title: Ride the Cog Railway
        description: Take the historic Cog up Pikes peak and enjoy the majestic beauty of Colorado.
      - title: Cave of the Winds
        description: Out door fun for all, enjoy tour caves discovered in 1881 or take part in the soaring adventures!
      - title: Tour the Garden of the Gods
        description: Drive through the landscapes and enjoy hiking trails throughout the amazing rock formations. Stop and the Vistors center or Garden of the Gods trading post for information, shopping and food.
      - title: Historic Downtown Manitou Springs
        description: Enjoy the day strolling beautiful and historic Manitou Springs with tons of eclectic shops and restaurants there is plenty of history to explore.
      - title: Pikes Peak Highway
        description: With an altitude of 14,115 feet above sea level, Pikes Peak forms a maginificent visual backdrop for Colorado Springs, Woodland Park, Fort Carson, the U.S. Air Force Academy, Garden of the Gods, Cripple Creek and many other regional cities and attractions.
      - title: Manitou Cliff Dwellings
        description: Discover hostory in the Native American cliff dwellings.
      - title: Cripple Creek
        description: Discover a true mining town. Casinos and fun for all!
    food:
      - title:
        description:
      - title:
        description:
      - title:
        description:
      - title:
        description:
      - title:
        description:
      - title:
        description:
      - title:
        description:
      - title:
        description:
      - title:
        description:

    drinks:
      - title:
        description:
      - title:
        description:
      - title:
        description:
      - title:
        description:
      - title:
        description:

  lbc: false

google:
  key: AIzaSyCn2Z9McwWAC-i_7FE0-ug5lN1M57gb0xo

#calendar:
#  ical: https://www.google.com/calendar/ical/baclig.com_fqi9g8u7mre0m4oaqj1p66608c%40group.calendar.google.com/public/basic.ics
#  google_id: baclig.com_fqi9g8u7mre0m4oaqj1p66608c@group.calendar.google.com
